apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pgsql-data-pvc
  namespace: gestion-produits
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
